Outfits/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('',views.HomePageView.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(redirect_authenticated_user=True),name='login'),
    #path('meh',views.CheckUserView,name='checkuser'),
    path('signup/',views.signup,name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('dashboard/<int:style>',views.DashboardView,name='dashboard'),
    path('newitem/',views.NewItemView.as_view(),name='newitem'),
    path('myclothes/',views.MyClothesView.as_view(),name='myclothes'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

PersonalStylist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Outfits.urls'))
]

Outfits/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from . import generate
from . import storage
from PIL import Image
import os

# Create your models here.
class ClothingItem(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    category = models.CharField(max_length = 20)
    name = models.CharField(max_length = 20)
    image = models.ImageField(default = 'default.jpg',upload_to='clothes_pics')

    def __str__(self):
        return "{}'s {}".format(self.user.username,self.name)
    
    def get_absolute_url(self):
        return reverse('dashboard',args=[0])
    
    def save(self):
        super().save()

        #Create Product
        project_id = "PersonalStylist"
        location =  "us-east1"
        product_id = self.user.username + "_" + str(self.id)
        product_set_id = self.user.username + "_PS"
        product_display_name = self.name
        product_category = "apparel"
        key = "category"
        value = self.category
        generate.create_product(project_id,location,product_id,product_display_name,product_category)

        #Add Product to Product Set
        generate.add_product_to_product_set(project_id,location,product_id,product_set_id)

        #Add product labels
        generate.update_product_labels(project_id,location,product_id,key,value)

        #Upload image to storage
        path = self.image.path 
        bucket = "clothmatching"
        file_name = self.name.replace(" ","") + str(self.id)
        storage.upload_blob(bucket,path,file_name)

        #Create Reference Image
        ref_id = "REFIMAGE-" + str(self.id)
        uri = "gs://clothmatching/" + file_name
        generate.create_reference_image(project_id,location,product_id,ref_id,uri)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)
        

class BadOutfit(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    items = models.ManyToManyField(ClothingItem)

    def __str__(self):
        return "Outfit:{}, Disliked by {}".format(self.id,self.user)


class PossibleItem(models.Model):
    category = models.CharField(max_length = 20,default='upper')
    name = models.CharField(max_length = 100,default='shirt')
    image = models.ImageField(default='default.jpg',upload_to='clothes_pics')

    def __str__(self):
        return "{}".format(self.name)
    
    def save(self):
        super().save()
        img = Image.open(self.image.path)
        
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class StyleOne(models.Model):
    #Alex Costa Youtube Channel
    season = models.CharField(max_length = 20)
    items = models.ManyToManyField(PossibleItem)
    
    def __str__(self):
        return "Alex Costa outfit #{}".format(self.id)

class StyleTwo(models.Model):
    #AlphaM Youtube Channel
    season = models.CharField(max_length = 20)
    items = models.ManyToManyField(PossibleItem)
    
    def __str__(self):
        return "AlphaM outfit #{}".format(self.id)

class StyleThree(models.Model):
    #TMF Youtube Channel
    season = models.CharField(max_length = 20)
    items = models.ManyToManyField(PossibleItem)
    
    def __str__(self):
        return "TMF outfit #{}".format(self.id)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Personal Stylist</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Navigation -->


    <!-- Header -->
    <header class="masthead">
        <div class="container d-flex h-100 align-items-center">
            <div class="mx-auto text-center">
                <h1 class="mx-auto my-0 text-uppercase">Personal Stylist</h1>
                <h2 style="color:white !important;" class="text-white-50 mx-auto mt-2 mb-5">A Smart way to choose your style </h2>
                {% if request.user.is_authenticated %}
                <a href="{% url 'dashboard' 0%}" class="btn btn-primary js-scroll-trigger">View Dashboard</a>
                <a href="{% url 'logout' %}" class="btn btn-primary js-scroll-trigger">Logout</a> {% else %}
                <a href="{% url 'login'%}" class="btn btn-primary js-scroll-trigger">Login</a>
                <a href="{% url 'signup'%}" class="btn btn-primary js-scroll-trigger">Create Account</a> {% endif %}
            </div>
        </div>
    </header>

    <!-- Bootstrap core JavaScript -->

    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->

    <!-- Custom scripts for this template -->

</body>

</html>

templates/myclothes.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Your Clothes</title>
    <meta charset="UTF-8">
    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" />
    <!-- Main Stylesheets -->
    <link rel="stylesheet" href="{% static 'css/viewclothes.css' %}" />
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>


    <!-- Header section -->
    <header class="header-section">
        <div class="container">
            <nav>
                <ul>
                    <li>
                        <a href="#" class="site-logo">
                            <h2 style="color:white;"></h2>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <!-- Shop section  -->
    <section class="shop-section">
        <center>
            <h1>Your Clothes</h1>
        </center>
        <div class="container">
            <div class="row">
                {% for cloth in clothes %} {% if cloth.user == user%}
                <div class="col-lg-3 col-sm-6">
                    <div class="shop-item">
                        <img src="{{MEDIA_URL}}{{cloth.image}}" alt="">
                        <h3>{{cloth.name}}</h3>
                    </div>
                </div>
                {% endif %} {% endfor %}
            </div>
        </div>
    </section>
    <!-- Shop section end -->




    <!-- Footer section -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                </div>
            </div>
        </div>
    </footer>


    <!--====== Javascripts & Jquery ======-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/viewclothes.js' %}"></script>

</body>

</html>

templates/newitem.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->

    <!-- Page Header -->
    <header class="masthead" style="background-color: #232323">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1 style="color: white !important">Add Item</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Navigation -->


    <!-- Form -->
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <tr>
                <th><label for="id_user">User:</label></th>
                <td><select class="form-control" name="user" required id="id_user">
          <option value={{request.user.id}} selected>{{request.user}}</option>
        
        </select></td>
            </tr>
            <br>
            <br>
            <tr>
                <th><label for="id_category">Category:</label></th>
                <td><input class="form-control" type="text" name="category" maxlength="20" required id="id_category"></td>
            </tr>
            <br>
            <br>
            <tr>
                <th><label for="id_name">Name:</label></th>
                <td><input class="form-control" type="text" name="name" maxlength="20" required id="id_name"></td>
            </tr>
            <br>
            <br>
            <tr>
                <th><label for="id_image">Image:</label></th>
                <td><input class="form-control-file" type="file" name="image" accept="image/*" id="id_image"></td>
            </tr>
            <br>
            <br>
            <center><input class="btn btn-primary" type="submit" value="Add Item to List"></center>
        </div>
    </form>
    <!-- Bootstrap core JavaScript -->

    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->

    <!-- Custom scripts for this template -->

</body>

</html>

templates/result.html
<html><body>
  <h1>Profiles</h1>
  <ul>
      {% for cloth in myclothes %}
<!--Name--><h3 id="name">{{cloth.name}}</h3><!--EndName-->
<!--Image--><img src = "{{MEDIA_URL}}{{cloth.image}}"><!--EndImage-->
      {% endfor %}
      <div class="clearfix">
        <center><a class="btn btn-primary" id = "myBtn" href="#">Checker</a></center>
    </div>
  </ul>
  <script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script>
    var newBtn = document.getElementById("myBtn");
          newBtn.onclick = function(){
          $.ajax({
            method:"GET",
            url: 'http://127.0.0.1:8000/apidata',
            success:function(data){
              
              // Stored all names in array
              itemNames = []
              //Store all images in Array
              itemImages = []
              //console.log(firstNewImage)
              //console.log(secondNewImage)
                //Change name and images of all items
              lines = data.split('\n')
              for (i=0;i<lines.length;i++){
                if (lines[i].startsWith('<!--Name')){
                  startingIndex = lines[i].indexOf('<h3')+14
                  endingIndex = lines[i].indexOf('</h3>')
                  itemNames.push(lines[i].slice(startingIndex,endingIndex))
                } else if(lines[i].startsWith('<!--Image')){
                  startingImageIndex = lines[i].indexOf('<img')
                  endingImageIndex = lines[i].indexOf('<!--End')
                  itemImages.push(lines[i].slice(startingImageIndex,endingImageIndex))
                }
              
              }
              for (i=0;i<itemNames.length;i++){
                  document.getElementsByTagName('h3')[i].innerHTML = itemNames[i]
                  document.getElementsByTagName('img')[i].outerHTML = itemImages[i]
              }
              console.log(itemImages)
            },
            failure: function(data){
              console.log('fail bro')
            }
          })
          //modal.style.display = "block";
        }
  </script>

  </body>
  </html>